### ISSUE TITLE
Create footer with a basic logo and a navbutton for a q&a

### ISSUE THREAD

**Issue by jmorales8** [jmorales8/Bunnys-space#16]

**Comment by GrpFruit** [comment]
Is it going to be the peach logo? Also what kind of footer are you thinking?
Footer examples: https://blog.hubspot.com/website/website-footer

**Comment by jmorales8** [comment]
> Is it going to be the peach logo? Also what kind of footer are you thinking? Footer examples: https://blog.hubspot.com/website/website-footer
> 
> [@jmorales8](https://github.com/jmorales8)

Imagine the Header we have on Telekit. That type of design but as a footer.

**Comment by GrpFruit** [comment]
Admin Portal** header type bar as a footer. Using the peach logo and adding Q&A button to footer navbar
