### ISSUE TITLE
Install Markdoc into UI

### ISSUE THREAD

**Issue by jmorales8** [jmorales8/Bunnys-space#19]
Install the markdoc into the project. Dont do any further work but to only install it

**Comment by GrpFruit** [comment]
Maybe this can be used on a how-to screen to help users follow their favorite streamers. Like a detailed step-by-step process in getting that feature working.

**Comment by jmorales8** [comment]
Once 

> getting

What do you mean? From following their favorite streamers? Can you expand on that?

**Comment by GrpFruit** [comment]
Yeah, I mean like just a guide on getting features to work in general. I think I remember you had plans for the Twitch Page to follow favorite streamers. I was using that as an example of what can use documentation for a step-by-step guide.
