### ISSUE TITLE
Add Star wars effect text in lore page

### ISSUE THREAD

**Issue by jmorales8** [jmorales8/Bunnys-space#26]
Add basic text, a lot of it to the lore page and allow it like this
https://starwarsintrocreator.kassellabs.io/#!/Episode9

Skip the intro of blue text but keep the star wars logo fadding away and the text from the bottom rising up

**Comment by GrpFruit** [comment]
@jmorales8 do you want me to recreate this with js and CSS or want me to use the link you gave to make a vid?
