### ISSUE TITLE
Convert tab icon to PEACH

### ISSUE THREAD

**Issue by jmorales8** [jmorales8/Bunnys-space#3]
Please change the fav icon from the bunny to this: 

Edit: Minor cleanup in profile file

**Comment by jmorales8** [comment]
![Image](https://github.com/jmorales8/Bunnys-space/assets/72041546/84ddc2d4-80ec-4a34-bab9-87fea96bc098)

**Comment by GrpFruit** [comment]
Is this change only for the profile or for all fav

**Comment by jmorales8** [comment]
> Is this change only for the profile or for all fav

For the entire project. On chrome. Put this img as the icon for the tabs in chrome
