### ISSUE TITLE
Create new buttons on navbar

### ISSUE THREAD

**Issue by jmorales8** [jmorales8/Bunnys-space#5]
Create new buttons and navlinks to lore page and a commision page

**Comment by GrpFruit** [comment]
Is the Question submission like an FAQ or Q&A? In my opinion, those wouldn't be on the navbar but more on a Contact page located in the footer. @jmorales8

**Comment by jmorales8** [comment]
> Reference

We currently don't have a footer, but that's a good idea. I'll create a ticket for a basic footer with links for those
